language: c

pre_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake pcp libpcp3-dev liblua5.1-0-dev
  - sudo /etc/init.d/pcp start
  - cd /var/lib/pcp/pmdas/sample/ && echo | sudo ./Install

install: true

script:
  - cmake . && make && make test