language: c
env:
  - CTEST_OUTPUT_ON_FAILURE=
sudo: required

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake pcp libpcp3-dev liblua5.1-0-dev
  - sudo /etc/init.d/pcp start
  - cd /var/lib/pcp/pmdas/sample/ && echo | sudo ./Install

script:
  - cd $TRAVIS_BUILD_DIR
  - cmake . && make && make test